# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/shuziluoji/bhw/work/FPGA-cameral/FPGA-cameral.cache/wt [current_project]
set_property parent.project_path D:/shuziluoji/bhw/work/FPGA-cameral/FPGA-cameral.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet d:/shuziluoji/bhw/work/FPGA-cameral/FPGA-cameral.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files d:/shuziluoji/bhw/work/FPGA-cameral/FPGA-cameral.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet d:/shuziluoji/bhw/work/FPGA-cameral/FPGA-cameral.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/shuziluoji/bhw/work/FPGA-cameral/FPGA-cameral.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/shuziluoji/bhw/work/code/sccb_sender.v
  D:/shuziluoji/bhw/work/code/reg_init.v
  D:/shuziluoji/bhw/work/code/vga_control.v
  D:/shuziluoji/bhw/work/code/display7.v
  D:/shuziluoji/bhw/work/code/deal_pic.v
  D:/shuziluoji/bhw/work/code/bluetooth.v
  D:/shuziluoji/bhw/work/code/camera_init.v
  D:/shuziluoji/bhw/work/code/vga_display.v
  D:/shuziluoji/bhw/work/code/camera_get_pic.v
  D:/shuziluoji/bhw/work/code/camera_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/shuziluoji/bhw/work/xdc/camera.xdc
set_property used_in_implementation false [get_files D:/shuziluoji/bhw/work/xdc/camera.xdc]


synth_design -top camera_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef camera_top.dcp

catch { report_utilization -file camera_top_utilization_synth.rpt -pb camera_top_utilization_synth.pb }
